[project]
name = "stacks-3ridge-seoul-meetup-2023"
authors = ["stacks-3ridge-seoul-meetup-2023-dev"]
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.stacks-3ridge-seoul-meetup-2023]
path = "contracts/stacks-3ridge-seoul-meetup-2023.clar"
depends_on = ["nft-trait", "commission-trait"]

[contracts.nft-trait]
path = "contracts/external/nft-trait.clar"
depends_on = []

[contracts.commission-trait]
path = "contracts/external/commission-trait.clar"
depends_on = []

[contracts.stacks-seoul-meetup-2023-commission]
path = "contracts/external/stacks-seoul-meetup-2023-commission.clar"
depends_on = []